### ISSUE TITLE
getMarketHistory two days old data 

### ISSUE THREAD

**Issue by Wildgear** [nuadi/googlecrestscript#13]
Every time I use the getMarketHistory command its pulling date for two days ago. I am unsure if its my end, google's, EVE's or the code. 

Thank you for this awesome Script

https://docs.google.com/spreadsheets/d/1aa1qpiJhC7jSVQRzoR_lUmGjQbHpRreAYoPBrk6zSmA/edit?usp=sharing

**Comment by nuadi** [comment]
This function was written by another developer. As a result, it will take me a little more time to debug this one but I will get started sorting this out.
