### ISSUE TITLE
(Feature Request) Possibility to narrow getMarketHistory to a station.

### ISSUE THREAD

**Issue by PLyczkowski** [nuadi/googlecrestscript#24]

**Comment by nuadi** [comment]
Unfortunately, this is not possible in the current version of CREST. The historical data is exactly what you see in the Price History tab for an item on the market, and gives us no options to refine the scope of that data. It is only regional at this time.

Furthermore, there is no way to identify when an order is sold or cancelled on the market. As a result, any third-party implementation of this sort of feature would be an approximation at best, and vulnerable to heavy manipulation.
