### ISSUE TITLE
(Feature Request) Possibility to read sell or buy order count with getMarketHistory.

### ISSUE THREAD

**Issue by PLyczkowski** [nuadi/googlecrestscript#25]

**Comment by nuadi** [comment]
You can using the `orderCount` argument. Here's an example that pulls the historical orders for PLEX in Jita.

`=getMarketHistory(29668,10000002,"orderCount")`

**Comment by PLyczkowski** [comment]
Yeah, but it gives you the total number of orders, not specifically sell or buy orders, right?

**Comment by nuadi** [comment]
Oh! Sorry, missed that detail. That is correct. There is no way to distinguish buy or sell status from this endpoint.

**Comment by PLyczkowski** [comment]
Alright.
