### ISSUE TITLE
Hey nuadi, is it me, or are all EVE API's often down/unresponsive?

### ISSUE THREAD

**Issue by PLyczkowski** [nuadi/googlecrestscript#26]
I mean CREST, eve marketdata and eve central.

**Comment by PLyczkowski** [comment]
(Now for instance crest and eve central api's seem down)

**Comment by nuadi** [comment]
I can't speak to EVE Marketdata or EVE Central since I don't use those. CREST is responding to me with no delay.

**Comment by PLyczkowski** [comment]
Ah, here is the answer: "Exception: Service invoked too many times for one day: urlfetch."

Probably because one countStationOrders run is one urlFetch?

**Comment by nuadi** [comment]
Oh, yes every count is a UrlFetch. You can only make 20,000 UrlFetch calls per day.
