### ISSUE TITLE
I is thewre an easy way to get all stationID.

### ISSUE THREAD

**Issue by Mezoti** [nuadi/googlecrestscript#27]
Hi
I would know if there is an way to get all RegionID and StationID sorted in one list/sheet.

I have been looking at the web to see of i could find some help in what data i can pull and how to do it, b/c i am real new to Crest, have in the past been using eve central, and want to build a new market trade sheet, and found your guide, very help full, many thanks in advance.

Best Regards
J J

**Comment by nuadi** [comment]
My script has a function named `getRegions` that will give you all of the region names and corresponding IDs. I do not know of a way to get all of the station IDs at once, but I'm still looking. In the meantime, you can use the `getOrdersAdv` function to pull orders and output the station IDs.

**Comment by Mezoti** [comment]
I have all ready been using the Getregions, but it is a huge job. :-)
