### ISSUE TITLE
[Request] getHistoryAdv needs a refresh parameter

### ISSUE THREAD

**Issue by misterDerpDerpDerp** [nuadi/googlecrestscript#31]
getHistoryAdv gives us a list of prices and volume at which an item was sold.

If you visit the same sheet a different day, the list does not automatically update. This means that the previous day's data is available on the server but not added to the google sheet using the getHistoryAdv function, unless I manually change one of the parameters.

It would be very useful to add a refresh parameter to it, which i can then tie to everything else I'm refreshing by referencing a particular cell.

**Comment by nuadi** [comment]
Have you tried adding a refresh option into the options you send in? That should cause a refresh.

**Comment by misterDerpDerpDerp** [comment]
Thanks! that works.

you may want to update your readme - it lists only the following options for getHistoryAdv:

>   A   B
> 1     itemId  29668
> 2     regionId    10000002
> 3     sortIndex   0
> 
> The available options are shown in the table below. All option keys are case sensitive.
> Option Key    Required?   Description
> itemId    Yes     The ID of the item to look for. Must be a number value.
> regionId  Yes     The region ID to look in. Must be a number value.
> days  no  Only return a given number of days. Default will return all historical data.
> headers   no  Set to FALSE to hide the headers. Default is TRUE.
> sortIndex     no  Number value for the column to sort. 0 = Location, 1 = Price (default), 2 = Volume, 3 = Location, and so on.
> sortOrder     no  Number value for sort order. 1 = Normal order (default for sell), -1 = Reverse order (default for buy)
> 4     sortOrder   -

**Comment by nuadi** [comment]
I will do that. Thanks for pointing that out.
