### ISSUE TITLE
Getchildren error?

### ISSUE THREAD

**Issue by wolfcat24** [nuadi/googlecrestscript#39]
I'm getting the following issue today:
"TypeError: Cannot call method "getchildren" of null. (line 121).

I've not messed with the script in any way personally, and certainly nothing has changed my end in the past week, when it's been working fine.

**Comment by nuadi** [comment]
Somehow I missed this. Can you tell me what function you were using when you hit this error?

**Comment by wolfcat24** [comment]
it was getting system prices...
I suspect it's because of eve central going down, and as such have bullied someone into switching it to pull esi.

**Comment by nuadi** [comment]
Okay. This script does not use EVE Central in any way, so it must have been a hiccup in CREST.

Update to the latest version of the script, and then let me know if it happens again. The new script uses the ESI endpoint for market orders now, so it should be a little more reliable than CREST going forward. Also, much faster.
