### ISSUE TITLE
Cost Index for Reactions

### ISSUE THREAD

**Issue by SubliminallyFamous** [nuadi/googlecrestscript#43]
Hi Nuadi, is it possible for you to add the cost index for reactions please?
eg. =getcostindex("system","reaction") 

Thanks
Sub

**Comment by nuadi** [comment]
Oh yeah. I'll add that.

**Comment by SubliminallyFamous** [comment]
Thanks! I'm horrible at the scripting part of this, so forgive me for asking, but will this all work after the CREST API is shut down on May 8th?
Cheers

**Comment by nuadi** [comment]
Nope. Some of it is still using CREST. That is still on my TODO list if I ever get time.

**Comment by SubliminallyFamous** [comment]
Alright, thanks for the info and for getting back to me so quick :)

**Comment by nuadi** [comment]
No problem. You got lucky. I'm waiting for my 3D printer to finish something, so I was browsing.

**Comment by SubliminallyFamous** [comment]
I do hope you get the time, I've used this script a lot and found it very helpful!

**Comment by nuadi** [comment]
Okay, so this is going to require a larger rewrite. That function is using CREST, so to get Reactions I would like to get ESI support for this - and they changed paradigms. I need to write a function to get all solar systems so you can get an ID, then pass that into the new getCostIndex function.

**Comment by SubliminallyFamous** [comment]
Literally understood three or four words from that ^^
