### ISSUE TITLE
Feature Request:Historical Volume Information

### ISSUE THREAD

**Issue by RichmonS** [nuadi/googlecrestscript#6]
I would like to add a feature request to be able to pull daily volume information for the item.

**Comment by nuadi** [comment]
Daily volume in terms of what's currently on the market, or historical volume?

**Comment by RichmonS** [comment]
I guess it would be historical volume.  There is volume data in the eve-central data and within the history charts on the market browser.  I am not even sure if it is available.

**Comment by nuadi** [comment]
Historical data is available. I'll add this to the milestones

**Comment by nuadi** [comment]
Feature has been added thanks to @jonberling. See #7 for detail.s
