### ISSUE TITLE
Alternate for how to do the oauth setup.

### ISSUE THREAD

**Issue by fuzzysteve** [nuadi/googlecrestscript#8]
https://gist.github.com/fuzzysteve/820cd2573d87a1d20d87 may be of interest, for how to get the oauth stuff handled a little more 'natively'

**Comment by nuadi** [comment]
Thanks for the heads up on this. I had taken a stab at the UI and OAuth, but couldn't get them to work, so fell back to something that did with the intent to revisit. This will help a lot. Thanks.
